/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.net.URLConnection;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class SobreProgramaView extends javax.swing.JInternalFrame {

    /**
     * Creates new form SobreProgramaView
     */
    public SobreProgramaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelFacebook = new javax.swing.JLabel();
        jLabelInsta = new javax.swing.JLabel();
        jLabelWhatsApp = new javax.swing.JLabel();
        jLabelLTwitter = new javax.swing.JLabel();
        jLabelLLinkdeIn = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setTitle("Sobre o Programa");

        jLabel1.setText("Programa desenvolvimento para uma Assistência Técnica especializada em Notebooks");

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logo_novaroma150-transp.png"))); // NOI18N
        jLabelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoMouseClicked(evt);
            }
        });

        jLabel2.setText("Faculdade Noa Roma");

        jLabel3.setText("Curso: Análise e Desenvolvimento de Sistemas");

        jLabel4.setText("Cadeira: Laboratório de Programação");

        jLabel5.setText("Professor(a): Liliane Fonseca");

        jLabel6.setText("Aluno(a): Rodrigo Ferreira Rodrigues");

        jLabel7.setText("Como projeto de P2 da cadeira de Laboratório de Programação.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Rodrigo Ferreira Rodrigues");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Redes Sociais");

        jLabelFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Facebook160px.png"))); // NOI18N
        jLabelFacebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFacebookMouseClicked(evt);
            }
        });

        jLabelInsta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Instagram121px.png"))); // NOI18N
        jLabelInsta.setToolTipText("@rfrodrigues");
        jLabelInsta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInstaMouseClicked(evt);
            }
        });

        jLabelWhatsApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/WhatsApp121px.png"))); // NOI18N
        jLabelWhatsApp.setToolTipText("+55 81 98855 - 7802");

        jLabelLTwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Twitter121px.png"))); // NOI18N
        jLabelLTwitter.setToolTipText("@rodrigo2208");
        jLabelLTwitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLTwitterMouseClicked(evt);
            }
        });

        jLabelLLinkdeIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/LinkedIn121px.png"))); // NOI18N
        jLabelLLinkdeIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLLinkdeInMouseClicked(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabelFacebook)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabelInsta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelWhatsApp))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(jLabel9))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel8))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(jLabelLLinkdeIn)
                            .addGap(18, 18, 18)
                            .addComponent(jLabelLTwitter)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(178, 178, 178))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInsta)
                    .addComponent(jLabelWhatsApp)
                    .addComponent(jLabelFacebook))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLLinkdeIn)
                    .addComponent(jLabelLTwitter))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelFacebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFacebookMouseClicked

        try {
            URL url = new URL("http://www.google.com");
            URLConnection connection = url.openConnection();
            connection.connect();
            Desktop.getDesktop().browse(new URI("https://web.facebook.com/rodrigo.ferreirarodrigues.1"));
        } catch (IOException | URISyntaxException e) {
            if (e.toString().substring(9, 29).equals("UnknownHostException")) {
                JOptionPane.showMessageDialog(this, "Você precisa estar conectado na internet");
            }
        }
    }//GEN-LAST:event_jLabelFacebookMouseClicked

    private void jLabelInstaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInstaMouseClicked
        try {
            URL url = new URL("http://www.google.com");
            URLConnection connection = url.openConnection();
            connection.connect();
            Desktop.getDesktop().browse(new URI("https://www.instagram.com/rfrodrigues/?hl=pt-br"));
        } catch (IOException | URISyntaxException e) {
            if (e.toString().substring(9, 29).equals("UnknownHostException")) {
                JOptionPane.showMessageDialog(this, "Você precisa estar conectado na internet");
            }
        }
    }//GEN-LAST:event_jLabelInstaMouseClicked

    private void jLabelLTwitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLTwitterMouseClicked
        try {
            URL url = new URL("http://www.google.com");
            URLConnection connection = url.openConnection();
            connection.connect();
            Desktop.getDesktop().browse(new URI("https://twitter.com/rodrigo2208"));
        } catch (IOException | URISyntaxException e) {
            if (e.toString().substring(9, 29).equals("UnknownHostException")) {
                JOptionPane.showMessageDialog(this, "Você precisa estar conectado na internet");
            }
        }
    }//GEN-LAST:event_jLabelLTwitterMouseClicked

    private void jLabelLLinkdeInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLLinkdeInMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelLLinkdeInMouseClicked

    private void jLabelLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoMouseClicked
        try {
            URL url = new URL("http://www.google.com");
            URLConnection connection = url.openConnection();
            connection.connect();
            Desktop.getDesktop().browse(new URI("http://www.faculdadenovaroma.com.br/"));
        } catch (IOException | URISyntaxException e) {
            if (e.toString().substring(9, 29).equals("UnknownHostException")) {
                JOptionPane.showMessageDialog(this, "Você precisa estar conectado na internet");
            }
        }
    }//GEN-LAST:event_jLabelLogoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFacebook;
    private javax.swing.JLabel jLabelInsta;
    private javax.swing.JLabel jLabelLLinkdeIn;
    private javax.swing.JLabel jLabelLTwitter;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelWhatsApp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
