package VIEW;

import CONTROLLER.BdGeralController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    BdGeralController bdGeralCtrl = new BdGeralController();

    /**
     * Construtor
     */
    public TelaPrincipal() {

        if (!bdGeralCtrl.verificaCaminhoGeral()) {
            int selecionaOpcao = JOptionPane.showConfirmDialog(null,
                    " Primeira execução do programa, criaremos as pastas no seu S.O e todos os arquivos necessários\n "
                    + " Clique em OK para criar os arquivos ou em CANCEL para sair do programa.\n"
                    + " Se não é a primeira execução, sua base está corrompida"
                    + " Clicando em OK, criaremos nova base zerada, se quiser procurar os arquivos"
                    + " Clique em CANCEL e jogue os arquivos manualmente na pasta base", null,
                    JOptionPane.OK_CANCEL_OPTION);
            if (selecionaOpcao == JOptionPane.OK_OPTION) {
                bdGeralCtrl.criaCaminhoBaseGeral();
                bdGeralCtrl.criaArquivoBaseClientesPF();
                bdGeralCtrl.criaArquivoBaseNotebook();
                bdGeralCtrl.criaArquivoBaseChamados();
                bdGeralCtrl.gravaListaBaseClientesPF();
                bdGeralCtrl.gravaListaBaseNotebook();
                bdGeralCtrl.gravaListaBaseChamados();
                if (bdGeralCtrl.verificaBaseClientesPF() && bdGeralCtrl.verificaBaseNotebook() && bdGeralCtrl.verificaBaseChamados()) {
                    JOptionPane.showMessageDialog(this, "Arquivos criados com sucesso, bem vindo ao Sistema!");
                    initComponents();
                    setExtendedState(JFrame.MAXIMIZED_BOTH);
                }
            } else if (selecionaOpcao == JOptionPane.CANCEL_OPTION) {
                JOptionPane.showMessageDialog(this, "Ação Cancelada, o programa será finalizado");
                System.exit(0);
            }
        } else {
            initComponents();
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
        //} else {
        //    JOptionPane.showMessageDialog(this, "BASE CORROMPIDA, O PROGRAMA SERÁ ENCERRADO");
        //    System.exit(0);
        //}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanel = new javax.swing.JDesktopPane();
        jMenuBarMenuPrincipal = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuArquivoSair = new javax.swing.JMenuItem();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuCadastroClientesG = new javax.swing.JMenu();
        jMenuCadastroClientesPF = new javax.swing.JMenuItem();
        jMenuCadastroFuncionarios = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RF Assistência Técnica");

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        jMenuArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/arquivo.png"))); // NOI18N
        jMenuArquivo.setMnemonic('a');
        jMenuArquivo.setText("Arquivo");

        jMenuArquivoSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuArquivoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/exit_power.png"))); // NOI18N
        jMenuArquivoSair.setMnemonic('s');
        jMenuArquivoSair.setText("Sair");
        jMenuArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuArquivoSair);

        jMenuBarMenuPrincipal.add(jMenuArquivo);

        jMenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/novo.png"))); // NOI18N
        jMenuCadastro.setMnemonic('c');
        jMenuCadastro.setText("Cadastro");

        jMenuCadastroClientesG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/users24px.png"))); // NOI18N
        jMenuCadastroClientesG.setMnemonic('t');
        jMenuCadastroClientesG.setText("Clientes");

        jMenuCadastroClientesPF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuCadastroClientesPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/users24px.png"))); // NOI18N
        jMenuCadastroClientesPF.setMnemonic('f');
        jMenuCadastroClientesPF.setText("Clientes PF");
        jMenuCadastroClientesPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroClientesPFActionPerformed(evt);
            }
        });
        jMenuCadastroClientesG.add(jMenuCadastroClientesPF);

        jMenuCadastro.add(jMenuCadastroClientesG);

        jMenuCadastroFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuCadastroFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/notebook24px.png"))); // NOI18N
        jMenuCadastroFuncionarios.setMnemonic('e');
        jMenuCadastroFuncionarios.setText("Equipamentos");
        jMenuCadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroFuncionariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastroFuncionarios);

        jMenuBarMenuPrincipal.add(jMenuCadastro);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/edit.png"))); // NOI18N
        jMenu1.setMnemonic('h');
        jMenu1.setText("Chamados");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/salvar.png"))); // NOI18N
        jMenuItem3.setMnemonic('a');
        jMenuItem3.setText("Menu Chamados");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBarMenuPrincipal.add(jMenu1);

        jMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/me.png"))); // NOI18N
        jMenuSobre.setMnemonic('b');
        jMenuSobre.setText("Sobre");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/help.png"))); // NOI18N
        jMenuItem2.setMnemonic('s');
        jMenuItem2.setText("Sobre o Programa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuSobre.add(jMenuItem2);

        jMenuBarMenuPrincipal.add(jMenuSobre);

        setJMenuBar(jMenuBarMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuArquivoSairActionPerformed

    private void jMenuCadastroClientesPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroClientesPFActionPerformed
        // TODO add your handling code here:
        ClientesPFView tela = new ClientesPFView();
        jDesktopPanel.add(tela);
        tela.setVisible(true);
        try {   
            tela.setSelected(true);   
            //diz que a janela interna é maximizável   
            tela.setMaximizable(true);   
            //set o tamanho máximo dela, que depende da janela pai   
            tela.setMaximum(true);   
        } catch (java.beans.PropertyVetoException e) {} 
    }//GEN-LAST:event_jMenuCadastroClientesPFActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        ChamadosView tela = new ChamadosView();
        jDesktopPanel.add(tela);
        tela.setVisible(true);
        try {
            tela.setSelected(true);   
            //diz que a janela interna é maximizável   
            tela.setMaximizable(true);   
            //set o tamanho máximo dela, que depende da janela pai   
            tela.setMaximum(true);   
        } catch (java.beans.PropertyVetoException e) {} 
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuCadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroFuncionariosActionPerformed
        // TODO add your handling code here:
        NotebooksView tela = new NotebooksView();
        jDesktopPanel.add(tela);
        tela.setVisible(true);
        try {   
            tela.setSelected(true);   
            //diz que a janela interna é maximizável   
            tela.setMaximizable(true);   
            //set o tamanho máximo dela, que depende da janela pai   
            tela.setMaximum(true);   
        } catch (java.beans.PropertyVetoException e) {} 
    }//GEN-LAST:event_jMenuCadastroFuncionariosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        SobreProgramaView tela = new SobreProgramaView();
        jDesktopPanel.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuItem jMenuArquivoSair;
    private javax.swing.JMenuBar jMenuBarMenuPrincipal;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuCadastroClientesG;
    private javax.swing.JMenuItem jMenuCadastroClientesPF;
    private javax.swing.JMenuItem jMenuCadastroFuncionarios;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jMenuSobre;
    // End of variables declaration//GEN-END:variables
}
